In [1]:
import pandas as pd

In [3]:
appl = pd.read_csv("full_history/AAPL.csv")

In [4]:
appl.head()

,date,open,high,low,close,adj close,volume
0,2023-12-28,194.139999,194.660004,193.169998,193.580002,193.580002,34014500
1,2023-12-27,192.490005,193.500000,191.089996,193.149994,193.149994,48087700
2,2023-12-26,193.610001,193.889999,192.830002,193.050003,193.050003,28919300
3,2023-12-22,195.179993,195.410004,192.970001,193.600006,193.600006,37122800
4,2023-12-21,196.100006,197.080002,193.500000,194.679993,194.679993,46482500

In [5]:
appl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10852 entries, 0 to 10851
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       10852 non-null  object
 1   open       10852 non-null  float64
 2   high       10852 non-null  float64
 3   low        10852 non-null  float64
 4   close      10852 non-null  float64
 5   adj close  10852 non-null  float64
 6   volume     10852 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 593.6+ KB

In [6]:
amzn  = pd.read_csv("full_history/AMZN.csv")
amzn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6700 entries, 0 to 6699
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       6700 non-null   object
 1   open       6700 non-null   float64
 2   high       6700 non-null   float64
 3   low        6700 non-null   float64
 4   close      6700 non-null   float64
 5   adj close  6700 non-null   float64
 6   volume     6700 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 366.5+ KB

In [7]:
nvda = pd.read_csv("full_history/NVDA.csv")
nvda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6275 entries, 0 to 6274
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       6275 non-null   object
 1   open       6275 non-null   float64
 2   high       6275 non-null   float64
 3   low        6275 non-null   float64
 4   close      6275 non-null   float64
 5   adj close  6275 non-null   float64
 6   volume     6275 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 343.3+ KB

In [8]:
nvda.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj close', 'volume'], dtype='object')

In [9]:
news = pd.read_csv("All_external.csv")
news.info()

KeyboardInterrupt:

In [ ]:
news.head()

,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
0,2020-06-05 06:30:54 UTC,Stocks That Hit 52-Week Highs On Friday,A,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-06-03 06:45:20 UTC,Stocks That Hit 52-Week Highs On Wednesday,A,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-05-26 00:30:07 UTC,71 Biggest Movers From Friday,A,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-05-22 08:45:06 UTC,46 Stocks Moving In Friday's Mid-Day Session,A,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-05-22 07:38:59 UTC,B of A Securities Maintains Neutral on Agilent...,A,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Appl_news = news[news['Stock_symbol'].str.contains('AAPL', case=False, na=False)]
Appl_news.head()

,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
6680,2020-06-10 07:33:26 UTC,Tech Stocks And FAANGS Strong Again To Start D...,AAPL,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,NaN,NaN,NaN,NaN,NaN,NaN
6681,2020-06-10 04:14:08 UTC,10 Biggest Price Target Changes For Wednesday,AAPL,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
6682,2020-06-10 03:53:47 UTC,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",AAPL,https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
6683,2020-06-10 03:19:25 UTC,"Deutsche Bank Maintains Buy on Apple, Raises P...",AAPL,https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
6684,2020-06-10 02:27:11 UTC,Apple To Let Users Trade In Their Mac Computer...,AAPL,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Appl_news.info()

<class 'pandas.core.frame.DataFrame'>
Index: 473 entries, 6680 to 2212401
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              473 non-null    object
 1   Article_title     473 non-null    object
 2   Stock_symbol      473 non-null    object
 3   Url               473 non-null    object
 4   Publisher         473 non-null    object
 5   Author            0 non-null      object
 6   Article           0 non-null      object
 7   Lsa_summary       0 non-null      float64
 8   Luhn_summary      0 non-null      float64
 9   Textrank_summary  0 non-null      float64
 10  Lexrank_summary   0 non-null      float64
dtypes: float64(4), object(7)
memory usage: 44.3+ KB

In [ ]:
file_path = '/Users/yashaswiaryan/Downloads/nasdaq_exteral_data.csv'
news_comp = pd.read_csv(file_path, chunksize=1000)
news_comp.head

:

In [5]:
chunks.columns

AttributeError: 'TextFileReader' object has no attribute 'columns'